### ISSUE TITLE
issue.null.name

### ISSUE THREAD

**Issue by dashaw92** [jad340/javaGameTemplate#2]
![12g12x](https://cloud.githubusercontent.com/assets/6251724/14503459/2f39ff80-017e-11e6-98e5-56e061dd3497.jpg)

**Comment by mshelto59** [comment]
We appreciate your overwhelming concern and outpouring of personal emotions. That said, I regret to inform you that this issue is being closed as it is solely based on third-party opinion and does not reflect the viewpoints or morals held by the creators of this project. Future meme-based trolling will not be tolerated.

Thank you and have a super awesome day.

**Comment by jad340** [comment]
Adding on to what @mshelto59 said, we would greatly appreciate any constructive criticism you would like to give that would improve this project, but simple meme-based trolling with no constructive attributes is not acceptable and will only result in your banning from further webscale contributions to this this 10x product that will disrupt many markets.
